[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    logged: run the test with an authenticated (logged-in) storage state
    crud: articles/comments CRUD operations
addopts = --tracing=retain-on-failure --screenshot=only-on-failure --video=retain-on-failure
